# Conclusion
After finishing analyzing the data in three different directions, I have a general answer to a couple of questions I envisioned at the beginning. California's drought levels have not been an improving trend over time. Different counties are experiencing different levels of drought, but overall they are at very dry levels. The economic damage caused by drought is very severe and is the most damaging of all natural disasters in California, so it is very necessary to put a lot of effort into studying and dealing with drought. 
Much of the limitations we encountered in our research stemmed from a lack of relevant expertise; we found a wealth of resources and data but it was not clear how to categorize and distill a range of data in order to support a clear direction for our research, which I think requires a certain amount of specific knowledge of geography and meteorological law.
Our future direction lies in the questions that we still haven't solved, the more detailed questions, such as what is the share of agricultural losses in terms of damage caused, and what are the links between the two.
