# Introduction

When I first came to the U.S. I heard the older man next to me on the plane talking to me about the drought in California, but at the time I knew very little about the specifics. So this time I like to choose this topic to help myself and others to know more about the drought in California.

In searching for data, I found more significance to this topic. California's history is closely tied to its environmental conditions, including drought. Examining this topic provides historical context to help us understand how past events have influenced current policies and societal attitudes toward water use and conservation. In addition, California's drought is a good example to familiarize us with a more visual and scientific approach to understanding global environmental issues and climate change.

Through this program we hope to answer the following key questions:
How have drought conditions in California changed over time? What are the current trends?
How have these drought conditions affected different counties in California?
What are the economic costs associated with these droughts, particularly in terms of agricultural losses and disaster management?
How can data on drought conditions inform decision-making and individual action plans?



